openapi: 3.0.0
x-stoplight:
  id: utvd8kedry3sp
info:
  title: Coffee Review API
  version: '1.0'
  description: |-
    This API allows you to create a user profile where you can write reviews of different coffees that you have tried.
    For now the brands and products are from the swedish selection.
servers:
  - url: 'http://localhost:5000'
paths:
  /coffee:
    get:
      summary: Your GET endpoint
      tags:
        - Standard usage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/coffees_reponse'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-coffee
      description: Returns all the coffee in API endpoint.
  /coffee/reviews:
    get:
      summary: Your GET endpoint
      tags:
        - Standard usage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review_response'
              examples:
                Example 1:
                  value:
                    reviews:
                      - coffee_id: '123'
                        id: 11
                        review: God och fräsch!
                        time_stamp: '2023-05-04 18:07:54'
                        user_id: 4
                      - coffee_id: '7310731101611'
                        id: 12
                        review: Smakrik
                        time_stamp: '2023-05-04 20:11:54'
                        user_id: 4
                      - coffee_id: '7310731101611'
                        id: 13
                        review: God och så!
                        time_stamp: '2023-05-04 20:36:49'
                        user_id: 4
        '500':
          description: Internal Server Error
      operationId: get-coffee-reviews
      description: Get all coffee reviews.
  '/coffee/reviews/{review_id}}':
    parameters:
      - schema:
          type: string
        name: review_id
        in: path
        required: true
        description: ID number of requested review.
    get:
      summary: Your GET endpoint
      tags:
        - Standard usage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review_response'
              examples:
                Example 1:
                  value:
                    reviews:
                      - id: 23
                        user_id: 32
                        coffee_id: '0672348832'
                        review: Too sweet!
                        time_stamp: '2023-04-13 08:40:21'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
              examples:
                Example 1:
                  value:
                    error: Review ID does not exist.
        '500':
          description: Internal Server Error
      operationId: get-coffee-reviews-review_id
      description: Returns a coffee review with id "review_id".
    put:
      summary: ''
      operationId: put-coffee-reviews-review_id
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/coffees_reponse'
      description: Change your previously written review if authorized.
      tags:
        - Authorized usage
      parameters:
        - schema:
            type: string
          in: header
          name: authentication
          description: Authentication token of the user owning the review.
  /coffee/search:
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/coffees_reponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-coffee-search
      tags:
        - Standard usage
      description: 'Search for a coffee product using a search_word parameter. Returns results of the search, zero or more coffee objects.'
      parameters:
        - schema:
            type: string
          in: query
          name: search_word
          description: Can be full or part of searched string.
  '/coffee/{coffee_id}':
    parameters:
      - schema:
          type: string
        name: coffee_id
        in: path
        description: Id of requested coffee.
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - Standard usage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/coffees_reponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
      operationId: get-coffee-coffee_id
      description: 'Returns information about coffee object with id: ''coffee_id''.'
      parameters: []
    post:
      summary: ''
      operationId: post-coffee-coffee_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review_response'
              examples:
                Example 1:
                  value:
                    reviews:
                      - id: 0
                        user_id: 0
                        coffee_id: string
                        review: string
                        time_stamp: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
        '500':
          description: Internal Server Error
      description: 'Post a new review for coffee product with id: ''coffee_id''. Needs to be an authorized user to post a review.'
      tags:
        - Authorized usage
      parameters:
        - schema:
            type: string
          in: header
          name: authentication
          description: Authentication token received from registering.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review_post'
            examples: {}
        description: Review body to add a coffee review to the database.
  '/coffee/{coffee_id}/reviews':
    parameters:
      - schema:
          type: string
        name: coffee_id
        in: path
        description: Id of requested coffee.
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - Standard usage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review_response'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
        '500':
          description: Internal Server Error
      operationId: get-coffee-coffee_id-reviews
      description: Get all reviews connected to a specific coffee id.
  /users:
    get:
      summary: Your GET endpoint
      tags:
        - Authorized usage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User_response'
              examples:
                Example 1:
                  value:
                    users:
                      - id: 32
                        username: allanwood
                        regTime: '2023-05-03 08:27:32'
      operationId: get-users
      description: Get all registered users. To be able to retreive all users you need to be have a authorization token. The request returns non-sensitive information only.
      parameters:
        - schema:
            type: string
          in: header
          name: authentication
          description: Token for authentication.
  /users/register:
    post:
      summary: Create New User
      operationId: post-users-register
      responses:
        '201':
          description: User Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  created:
                    type: object
                    x-stoplight:
                      id: lxqhbzaowcrn4
                    properties:
                      id:
                        type: integer
                        x-stoplight:
                          id: 76d7wha1u5s6w
                      username:
                        type: string
                        x-stoplight:
                          id: l7lney34ct2vv
                      email:
                        type: string
                        x-stoplight:
                          id: qe24u1d1763ke
                      token:
                        type: string
                        x-stoplight:
                          id: opv4zf6fvkypx
              examples:
                Example 1:
                  value:
                    created:
                      id: 32
                      username: allanwood
                      email: allanwood@gmail.com
                      token: uaRkfY&kand#kaS==
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
              examples:
                Example 1:
                  value:
                    error: Missing required parameters.
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
              examples:
                Example 1:
                  value:
                    error: Username already exists.
        '500':
          description: Internal Server Error
      requestBody:
        content: {}
        description: Post the necessary fields for the API to create a new user.
      description: Register a new user and recieve a personal token for future authorization usage.
      parameters:
        - schema:
            type: string
          in: query
          name: username
          description: First and last name of user.
        - schema:
            type: string
          in: query
          name: email
          description: email address of the user.
      tags:
        - Standard usage
    parameters: []
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Your GET endpoint
      operationId: get-users-userId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User_response'
              examples:
                Example 1:
                  value:
                    users:
                      - id: 35
                        username: allanwood
                        regTime: '2019-08-24T14:15:22Z'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
              examples:
                Example 1:
                  value:
                    error: User does not exist
        '500':
          description: Internal Server Error
      description: Returns non-sensitive information about user with "user_id".
      requestBody:
        content: {}
      tags:
        - Authorized usage
  '/users/{user_id}/reviews':
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        description: id of user to filter by.
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - Standard usage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review_response'
              examples:
                Example 1:
                  value:
                    reviews:
                      - id: 11
                        user_id: 23
                        coffee_id: '7766500382'
                        review: Very stasty!
                        time_stamp: '2023-04-18 12:45:13'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
              examples:
                Example 1:
                  value:
                    error: User does not exist.
        '500':
          description: Internal Server Error
      operationId: get-users-user_id-reviews
      description: Returns all reviews made by user with id "user_id".
components:
  schemas:
    User:
      title: User
      type: object
      x-examples:
        Example 1:
          id: 32
          username: allanwood
          regTime: '2023-05-03 08:34:52'
      description: Non-sensitive user information.
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        username:
          type: string
          x-stoplight:
            id: huecktyltfwwm
        regTime:
          type: string
          description: The date that the user was created.
          x-stoplight:
            id: e350m60vvidkb
          format: date-time
      required:
        - id
        - username
    coffee:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        url:
          type: string
      x-examples:
        Example 1:
          id: '7310731101611'
          name: ZOÉGAS Hazienda - 450 G
          url: 'https://www.dittsvenskaskafferi.se/zogas-hazienda-450g-7310731101611'
      title: ''
      description: Coffee object in JSON database.
    coffees_reponse:
      type: object
      x-examples:
        Example 1:
          coffee:
            - id: '7310731101611'
              name: ZOÉGAS Hazienda - 450 G
              url: 'https://www.dittsvenskaskafferi.se/zogas-hazienda-450g-7310731101611'
            - id: '7310731101888'
              name: ZOÉGAS Västkust - 450 G
              url: 'https://www.dittsvenskaskafferi.se/zogas-vstkust-450g-7310731101888'
            - id: '7310731102397'
              name: ZOÉGAS KAHAWA - 450G
              url: 'https://www.dittsvenskaskafferi.se/zogas-kahawa-450g-7310731102397'
      properties:
        coffee:
          type: array
          items:
            $ref: '#/components/schemas/coffee'
      description: Dictionary structure of coffee objsects returned from JSON database.
    APIClientError:
      title: APIClientError
      x-stoplight:
        id: 677it1bo9d2bu
      type: object
      x-examples:
        Example 1:
          error: Missing required parameters.
      description: Client error response with message of the error.
      properties:
        error:
          type: string
          x-stoplight:
            id: 3c6uh7y205c3b
      required:
        - error
    Review_post:
      title: Review_post
      x-stoplight:
        id: i94ymw5f8qhtq
      type: object
      description: Structure of review body when posting a new review.
      properties:
        review:
          type: string
          x-stoplight:
            id: 0kylrqxqg8x2z
      x-examples:
        Example 1:
          review: Tasteful!
    Review_response:
      type: object
      x-stoplight:
        id: 51zia3ngj2iaq
      x-examples:
        Example 1:
          reviews:
            - coffee_id: 7310731101611
              id: 12
              review: Smakrik
              time_stamp: '2023-05-04 20:11:54'
              user_id: 4
            - coffee_id: 7310731101611
              id: 13
              review: Smakrik
              time_stamp: '2023-05-04 20:36:49'
              user_id: 4
      properties:
        reviews:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              user_id:
                type: integer
              coffee_id:
                type: string
              review:
                type: string
              time_stamp:
                type: string
      description: Response structure of reviews returned on get request.
      title: Review response
    User_response:
      type: object
      x-examples:
        Example 1:
          users:
            - id: 32
              username: allanwood
              regTime: '2023-05-03 08:27:32'
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
      description: Response structure of user request.
tags:
  - name: Authorized usage
    description: API URL where authorization is required.
  - name: Standard usage
    description: API URL available without authorization.
